import { test, expect, Page } from '@playwright/test';
const password = 'RecruiterPassword123!';
async function menu(page: Page, name: string) {
  await page.getByRole('button', { name: 'Abrir menu' }).click();
  await page.locator('nav').getByText(name, { exact: true }).click();
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
}
test('recruiter can register, manage the team and track work through the existing UI', async ({ page, request }) => {
  const suffix = Date.now();
  const ownerEmail = 'owner-' + suffix + '@example.test';
  const memberEmail = 'member-' + suffix + '@example.test';
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Criar uma organização' }).click();
  await page.getByLabel('Seu nome').fill('Recrutador');
  await page.getByLabel('Organização', { exact: true }).fill('Equipe de avaliação');
  await page.getByLabel('E-mail', { exact: true }).fill(ownerEmail);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'CRIAR CONTA', exact: true }).click();
  await expect(page.getByText('Olá, Recrutador!')).toBeVisible();
  await menu(page, 'COLABORADORES');
  await page.getByRole('button', { name: 'Novo colaborador', exact: true }).click();
  const member = page.getByRole('form', { name: 'Novo colaborador' });
  await member.getByLabel('Nome', { exact: true }).fill('Pessoa do time');
  await member.getByLabel('E-mail').fill(memberEmail);
  await member.getByLabel('Senha inicial').fill(password);
  await member.getByRole('button', { name: 'Adicionar colaborador' }).click();
  await expect(member).not.toBeVisible();
  await expect(page.getByText('Pessoa do time', { exact: true })).toBeVisible();
  await menu(page, 'PROJETOS');
  await page.getByRole('button', { name: 'Novo projeto', exact: true }).click();
  await page.getByPlaceholder('Nome do Projeto').filter({ visible: true }).fill('API de pedidos');
  await page.getByRole('button', { name: 'CRIAR', exact: true }).filter({ visible: true }).click();
  await expect(page.getByText('API de pedidos', { exact: true }).filter({ visible: true })).toBeVisible();
  await menu(page, 'TAREFAS');
  await page.getByRole('button', { name: 'Nova tarefa' }).click();
  const taskForm = page.locator('form').filter({ has: page.getByRole('heading', { name: 'Criar Tarefa:' }) });
  await taskForm.getByPlaceholder('Nome da Tarefa').fill('Corrigir cálculo do pedido');
  await taskForm.getByPlaceholder('Descrição da Tarefa').fill('Reproduzir o erro e corrigir a API.');
  await taskForm.locator('select').nth(0).selectOption({ label: 'API de pedidos' });
  await taskForm.locator('select').nth(1).selectOption({ label: 'Pessoa do time' });
  await taskForm.getByRole('button', { name: 'CRIAR', exact: true }).click();
  await expect(taskForm).not.toBeVisible();
  await expect(page.getByText('Corrigir cálculo do pedido', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.getByRole('button', { name: 'Editar tarefa', exact: true }).click();
  await page.getByPlaceholder('Nome da Tarefa').filter({ visible: true }).fill('Corrigir total do pedido');
  await expect(page.getByPlaceholder('Nome da Tarefa').filter({ visible: true })).toHaveValue('Corrigir total do pedido');
  await page.getByRole('button', { name: 'CONFIRMAR', exact: true }).filter({ visible: true }).click();
  await expect(page.getByText('Corrigir total do pedido', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.getByRole('button', { name: 'Iniciar', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Finalizar', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Finalizar', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Finalizar', exact: true })).not.toBeVisible();
  const token = await page.evaluate(() => sessionStorage.getItem('neotasks:token'));
  const headers = { Authorization: 'Bearer ' + token };
  const tasks = await (await request.get('/app-api/tasks', { headers })).json();
  const finishedAt = new Date();
  expect((await request.post('/app-api/timetrackers', { headers, data: {
    taskId: tasks[0].id, startDate: new Date(finishedAt.getTime() - 25 * 60000).toISOString(), endDate: finishedAt.toISOString(),
  } })).status()).toBe(201);
  const extra = await request.post('/app-api/tasks', { headers, data: {
    name: 'Investigar pagamento', projectId: tasks[0].project.id,
    startDate: new Date(finishedAt.getTime() - 15 * 60000).toISOString(), endDate: finishedAt.toISOString(),
  } });
  expect(extra.status()).toBe(201);
  await page.reload();
  await menu(page, 'RELATÓRIO');
  await expect(page.getByRole('row').filter({ hasText: 'Corrigir total do pedido' })).toContainText('00:25');
  await expect(page.getByRole('row').filter({ hasText: 'Investigar pagamento' })).toContainText('00:15');
  await page.getByRole('button', { name: 'Filtrar relatório' }).click();
  await page.getByPlaceholder('Digite sua busca').fill('Investigar');
  await expect(page.getByRole('row').filter({ hasText: 'Investigar pagamento' })).toContainText('00:15');
  await expect(page.getByRole('row').filter({ hasText: 'Corrigir total do pedido' })).not.toBeVisible();
  await page.reload();
  await expect(page.getByText('Olá, Recrutador!')).toBeVisible();
  await page.getByRole('button', { name: 'Sair', exact: true }).click();
  await page.getByLabel('E-mail', { exact: true }).fill(memberEmail);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'ENTRAR', exact: true }).click();
  await expect(page.getByText('Olá, Pessoa do time!')).toBeVisible();
  await menu(page, 'PROJETOS');
  await expect(page.getByRole('button', { name: 'Novo projeto' })).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Editar projeto' })).not.toBeVisible();
  await menu(page, 'TAREFAS');
  await expect(page.getByText('Corrigir total do pedido', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.getByRole('button', { name: 'Excluir tarefa', exact: true }).first().click();
  await page.getByRole('button', { name: 'EXCLUIR', exact: true }).filter({ visible: true }).click();
  await expect(page.getByText('Corrigir total do pedido', { exact: true }).filter({ visible: true })).not.toBeVisible();
  expect(errors).toEqual([]);
});
test('PostgreSQL survives an API container restart', async ({ request }) => {
  const registration = await request.post('/app-api/register', { data: { name: 'Persistence test', organization: 'Persistence', email: 'persist-' + Date.now() + '@example.test', password } });
  expect(registration.status()).toBe(201);
  const { token } = await registration.json();
  const headers = { Authorization: 'Bearer ' + token };
  const project = await request.post('/app-api/projects', { headers, data: { name: 'Persisted project' } });
  expect(project.status()).toBe(201);
  const { id } = await project.json();
  const { execFileSync } = await import('node:child_process');
  execFileSync('docker', ['compose', '-f', '../compose.yaml', 'restart', 'db', 'api']);
  await expect.poll(async () => { try { return (await request.get('/health')).status(); } catch { return 0; } }, { timeout: 30000 }).toBe(200);
  const projects = await request.get('/app-api/projects', { headers });
  expect(projects.status()).toBe(200);
  expect((await projects.json()).some((item: { id: string }) => item.id === id)).toBe(true);
});
